### ISSUE TITLE
テストコードを書く

### ISSUE THREAD

**Issue by KentoBF5587** [KentoBF5587/bookstore_visitor#89]
テストコードを書く
- [x] モデルスペック一部完了
- [ ] システムスペック

**Comment by KentoBF5587** [comment]
お疲れ様です。
本リリースは終わりましたが、テストコードを書く際に詰まってしまっており、もし大丈夫であれば質問しても宜しいでしょうか？

**実装したいもの・解決したいもの：**
システムスペックのテストを書けるための準備（モデルスペックはいくつか書いてテスト機能も動きます）

**エラー内容**

```
services.web.depends_on.chrome condition is required
```
↑ターミナルで表示されます

**エラーの意味とエラー内容から推測される原因**

compose.ymlファイルの記述に問題があるという推測です。
元々の箇所が、

```yml
depends_on:
      db:
        condition: service_healthy
```

となっているため
```yml
depends_on:
      chrome:
        condition: service_healthy
      db:
        condition: service_healthy
```

と書くのかとも思いましたが、chromeにはservice_healthyを使わないという事を知り、また参考にした記事でも特に service_healthyを特に設定していなかったので、これではないかなと考えています。

**実装する際に参考にした資料：**

[https://hackmd.io/@SKjw2RY-RNCUNSdJfEWPig/HJE0GUClC](rails newからデプロイするまでやってみよう)
RUNTEQカリキュラムの「RSpec入門・演習」のリポジトリ

**エラーを解決するために調べた資料**
[https://qiita.com/masarashi/items/84761a4e8de494f4d073](【Rails6】Docker環境でRSpecのシステムスペックを実行する)




**補足**
現在以下のように進めております。

* Gemfileに、すでにインストールされていたcapybaraとselenium-webdriverに加え、webdriversを追記しbundle install。
* 隠しファイル.rspecに --format documentationと書く。

この2点を済ませた上に、compose.ymlファイルに必要事項を追記しようとカリキュラムを参考に

* services > web > environment 下に SELENIUM_DRIVER_URLの追記

* services > web > depends_on  下に chrome: {} の追記

* services > chrome 下に image, portsの追記

こちらの3点を付け加えて以下のように書きました

```yml
version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d bookstore_visitor_development -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && bundle exec rails db:prepare && rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/bookstore_visitor
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000"
    depends_on:
      chrome: {}
      db:
        condition: service_healthy
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444
volumes:
  bundle_data:
  postgresql_data:
  node_modules:
```
